import { describe, expect, it, vi } from 'vitest';
import type { GameKey, WishItem } from '../src/types.ts';

// The generated manifest (src/data/wishes/portraits/hsr.ts) is regenerated by
// `npm run gen:portraits` and its exact contents have their own tests
// (tests/portraitManifest.test.ts). Mocking it here decouples the resolver's
// *logic* tests from whichever names the wiki happens to host this week, and
// lets us add one synthetic NFD/NFC pair the real manifest has no need for
// (its only non-ASCII character is the bullet, which has no decomposition).
const FAKE_HSR_NAMES = new Set([
  'Acheron',
  'Kafka',
  "It's Showtime",
  'Himeko • Nova',
  'Dan Heng • Imbibitor Lunae',
  'Ninja Record: Sound Hunt',
  'What Is Real?',
  'Woof! Walk Time!',
  'Café Ohno',
]);

vi.mock('../src/data/wishes/portraits/hsr.ts', () => ({
  HSR_PORTRAIT_NAMES: FAKE_HSR_NAMES,
}));

const { portraitUrl } = await import('../src/data/wishes/portraits/resolve.ts');

function makeItem(overrides: Partial<WishItem> = {}): WishItem {
  return {
    id: '1',
    bannerType: '11',
    name: 'Acheron',
    itemType: 'Character',
    rank: '5',
    time: '2026-01-01 00:00:00',
    ...overrides,
  };
}

const hsr: GameKey = 'hsr';

describe('portraitUrl — matching', () => {
  it('matches an exact verbatim name', () => {
    expect(portraitUrl(makeItem({ name: 'Acheron' }), hsr)).not.toBeNull();
  });

  it('matches a bullet-bearing name unmodified', () => {
    expect(portraitUrl(makeItem({ name: 'Himeko • Nova' }), hsr)).not.toBeNull();
    expect(portraitUrl(makeItem({ name: 'Dan Heng • Imbibitor Lunae' }), hsr)).not.toBeNull();
  });

  it('matches an ASCII-apostrophe name, but not a smart-quoted variant', () => {
    expect(portraitUrl(makeItem({ name: "It's Showtime", itemType: 'Light Cone' }), hsr)).not.toBeNull();
    // U+2019 RIGHT SINGLE QUOTATION MARK — a different character from the
    // manifest's real U+0027 apostrophe, and must not be treated as the same.
    expect(portraitUrl(makeItem({ name: 'It’s Showtime', itemType: 'Light Cone' }), hsr)).toBeNull();
  });

  it('still matches with leading/trailing whitespace on the stored name', () => {
    expect(portraitUrl(makeItem({ name: '  Acheron  ' }), hsr)).not.toBeNull();
  });

  it('matches an NFD-composed name against its NFC manifest key', () => {
    // 'e' + combining acute accent (U+0301), decomposed — the manifest key
    // 'Café Ohno' is the single-codepoint NFC form.
    expect(portraitUrl(makeItem({ name: 'Café Ohno' }), hsr)).not.toBeNull();
  });

  it('returns null for a name absent from the manifest', () => {
    expect(portraitUrl(makeItem({ name: 'Not A Real Character' }), hsr)).toBeNull();
  });
});

describe('portraitUrl — URL construction', () => {
  it('builds the full CDN URL for a matched character', () => {
    expect(portraitUrl(makeItem({ name: 'Kafka' }), hsr)).toBe(
      'https://static.wikia.nocookie.net/houkai-star-rail/images/8/8c/Character_Kafka_Icon.png' +
        '/revision/latest/scale-to-width-down/64',
    );
  });

  it('hashes a colon-bearing name to the colon-stripped directory', () => {
    const url = portraitUrl(makeItem({ name: 'Ninja Record: Sound Hunt', itemType: 'Light Cone' }), hsr);
    expect(url).toContain('/images/8/88/');
    expect(url).not.toContain('/images/2/23/');
  });

  it('strips a question mark the same way', () => {
    const url = portraitUrl(makeItem({ name: 'What Is Real?', itemType: 'Light Cone' }), hsr);
    expect(url).toContain('/Light_Cone_What_Is_Real_Icon.png/');
    expect(url).not.toContain('%3F');
  });

  it('hashes a bullet name to 2/2a, pinning MD5 UTF-8 handling', () => {
    const url = portraitUrl(makeItem({ name: 'Dan Heng • Imbibitor Lunae' }), hsr);
    expect(url).toContain('/images/2/2a/');
  });

  it('uses the houkai-star-rail CDN segment, never honkai-star-rail', () => {
    const url = portraitUrl(makeItem({ name: 'Kafka' }), hsr)!;
    expect(url).toContain('/houkai-star-rail/');
    expect(url).not.toContain('honkai-star-rail');
  });

  it('percent-encodes a bang-bearing name to %21', () => {
    const url = portraitUrl(makeItem({ name: 'Woof! Walk Time!', itemType: 'Light Cone' }), hsr);
    expect(url).toContain('Woof%21_Walk_Time%21');
  });
});

describe('portraitUrl — gates', () => {
  it('never resolves a 3★ item, even when its name is in the manifest', () => {
    expect(portraitUrl(makeItem({ name: 'Acheron', rank: '3' }), hsr)).toBeNull();
  });

  it('resolves both 4★ and 5★', () => {
    expect(portraitUrl(makeItem({ name: 'Acheron', rank: '4' }), hsr)).not.toBeNull();
    expect(portraitUrl(makeItem({ name: 'Acheron', rank: '5' }), hsr)).not.toBeNull();
  });

  it('never reaches the manifest for weapon, wengine, bangboo, or a blank itemType', () => {
    const hasSpy = vi.spyOn(FAKE_HSR_NAMES, 'has');
    try {
      expect(portraitUrl(makeItem({ name: 'Kafka', itemType: 'Weapon' }), hsr)).toBeNull();
      expect(portraitUrl(makeItem({ name: 'Kafka', itemType: 'W-Engine' }), hsr)).toBeNull();
      expect(portraitUrl(makeItem({ name: 'Kafka', itemType: 'Bangboo' }), hsr)).toBeNull();
      expect(portraitUrl(makeItem({ name: 'Kafka', itemType: '' }), hsr)).toBeNull();
      expect(hasSpy).not.toHaveBeenCalled();
    } finally {
      hasSpy.mockRestore();
    }
  });

  it('resolves nothing for a game with no PORTRAIT_CONFIGS entry', () => {
    expect(portraitUrl(makeItem({ name: 'Kafka' }), 'genshin')).toBeNull();
    expect(portraitUrl(makeItem({ name: 'Kafka' }), 'zzz')).toBeNull();
  });
});
