/**
 * Regenerates the committed portrait-name manifests under
 * `src/data/wishes/portraits/` — the record of which item names Fandom
 * actually hosts an icon for.
 *
 * Run: `npm run gen:portraits` (add `-- --force` to accept removals).
 *
 * **Never** invoked by `npm run build`, or by anything else in the build. A
 * build must not touch the network; this is a by-hand (and weekly-CI) chore
 * whose whole output is a reviewable diff.
 *
 * Like scripts/smoke.ts it sends a descriptive User-Agent, because Fandom
 * 403s bot-like default UAs outside a browser.
 */
import { existsSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { api } from '../src/data/wiki/client.ts';
import { GAME_CONFIGS, GAME_KEYS, USER_AGENT } from '../src/data/wiki/games.ts';
import { ICON_SUFFIX, PORTRAIT_CONFIGS, storedFilename } from '../src/data/wishes/portraits/config.ts';
import type { GameKey } from '../src/types.ts';

/** Refuse to loop forever if a wiki keeps handing back continuation tokens. */
const MAX_PAGES = 60;

/**
 * Recovers the item name from a file title, or null if this file isn't a
 * square item icon at all. Accepts both shapes the API hands back: the
 * underscored `name` from `allimages` and the `File:`-prefixed, spaced
 * `title` from `allpages`.
 */
export function nameFromTitle(rawTitle: string, prefix: string): string | null {
  const title = rawTitle.replace(/^File:/, '').replace(/_/g, ' ');
  const head = `${prefix} `;
  if (!title.startsWith(head) || !title.endsWith(ICON_SUFFIX)) return null;
  const name = title.slice(head.length, title.length - ICON_SUFFIX.length).trim().normalize('NFC');
  return name || null;
}

export interface WritePlan {
  added: string[];
  /** Names in the committed set the fresh sweep did not return — the miss list. */
  removed: string[];
  write: boolean;
  refused: boolean;
}

/**
 * Decides what a run does with its sweep results.
 *
 * Additions land on their own; any removal stops the run dead until a human
 * has read the names and re-run with `--force`. A silent overwrite on a
 * transient wiki hiccup would quietly delete a working entry, and nothing
 * distinguishes "Fandom removed this" from "that call had a bad day".
 */
export function planWrite(committed: ReadonlySet<string> | null, fresh: ReadonlySet<string>, force: boolean): WritePlan {
  const added = [...fresh].filter((name) => !committed?.has(name)).sort();
  const removed = committed ? [...committed].filter((name) => !fresh.has(name)).sort() : [];
  const refused = removed.length > 0 && !force;
  return { added, removed, refused, write: !refused && (added.length > 0 || removed.length > 0) };
}

function quote(name: string): string {
  return name.includes("'") ? JSON.stringify(name) : `'${name.replace(/\\/g, '\\\\')}'`;
}

function constName(game: GameKey): string {
  return `${game.toUpperCase()}_PORTRAIT_NAMES`;
}

export function renderManifest(game: GameKey, names: string[]): string {
  const sorted = [...names].sort();
  return (
    `/**\n` +
    ` * ${GAME_CONFIGS[game].label} portrait-name manifest: every item name the wiki\n` +
    ` * hosts a square icon for. Membership is the whole value — the URL is a pure\n` +
    ` * function of the name (src/data/wishes/portraits/config.ts), so storing one\n` +
    ` * per entry would only be redundant.\n` +
    ` *\n` +
    ` * Generated by \`npm run gen:portraits\` — do not edit by hand.\n` +
    ` */\n` +
    `export const ${constName(game)}: ReadonlySet<string> = new Set([\n` +
    sorted.map((name) => `  ${quote(name)},\n`).join('') +
    `]);\n`
  );
}

function manifestUrl(game: GameKey): URL {
  return new URL(`../src/data/wishes/portraits/${game}.ts`, import.meta.url);
}

async function readCommitted(game: GameKey): Promise<Set<string> | null> {
  const url = manifestUrl(game);
  if (!existsSync(fileURLToPath(url))) return null; // first run for this game

  // Anything else — a truncated write, a merge conflict, a renamed export — is
  // a real failure. Swallowing it would make the committed set look empty, so
  // every existing name would read as an addition and §3.2's refusal never
  // fires: exactly the silent destructive overwrite this script exists to stop.
  const module = await import(`${url.href}?t=${Date.now()}`);
  const names = module[constName(game)];
  if (!names) {
    throw new Error(`${fileURLToPath(url)} does not export ${constName(game)}`);
  }
  return new Set<string>(names);
}

/** MediaWiki's own filename spelling, from either API shape. */
function underscored(rawTitle: string): string {
  return rawTitle.replace(/^File:/, '').replace(/ /g, '_');
}

/**
 * The names one category's two sweeps between them vouch for: `icons` from
 * real uploads, `spellings` from file redirects.
 *
 * A redirect earns its place only if it resolves to a filename we actually saw
 * uploaded. That is true for the punctuated in-game spellings the redirect
 * sweep exists to recover (`Ninja Record: Sound Hunt` → the colon-less upload)
 * and false for everything else it drags in — `Kafka (Currency Wars)` minigame
 * cards, alternate spellings like `Topaz and Numby`, casing variants.
 *
 * The filter is not cosmetic. A redirect is a wiki page, not a CDN object, so
 * an unvouched name hashes to a directory holding nothing; Fandom answers that
 * with a 404 whose decoy body still fires the `<img>`'s `load` event, which
 * would paint a placeholder graphic over the category glyph instead of falling
 * back to it (measured: 98 such names, all 404).
 */
export function namesFromSweeps(
  prefix: string,
  uploadTitles: string[],
  redirectTitles: string[],
): { icons: string[]; spellings: string[] } {
  const uploaded = new Set(uploadTitles.map(underscored));

  const icons = new Set<string>();
  for (const title of uploadTitles) {
    const name = nameFromTitle(title, prefix);
    if (name) icons.add(name);
  }

  const spellings = new Set<string>();
  for (const title of redirectTitles) {
    const name = nameFromTitle(title, prefix);
    if (name && !icons.has(name) && uploaded.has(storedFilename(prefix, name))) spellings.add(name);
  }

  return { icons: [...icons], spellings: [...spellings] };
}

/** Walks a `list=` query to exhaustion, following continuation tokens. */
async function sweep(host: string, list: string, params: Record<string, string | number>): Promise<string[]> {
  const titles: string[] = [];
  let cont: Record<string, string> = {};
  for (let page = 0; page < MAX_PAGES; page++) {
    const data = await api(host, { action: 'query', list, ...params, ...cont }, USER_AGENT);
    for (const entry of data.query?.[list] ?? []) {
      const title = entry.title ?? entry.name;
      if (typeof title === 'string') titles.push(title);
    }
    if (!data.continue) return titles;
    cont = data.continue;
  }
  throw new Error(`${host}: list=${list} still paginating after ${MAX_PAGES} requests`);
}

async function sweepGame(game: GameKey): Promise<Set<string>> {
  const host = GAME_CONFIGS[game].host;
  const { filePrefixes } = PORTRAIT_CONFIGS[game]!;
  const names = new Set<string>();

  for (const [kind, prefix] of Object.entries(filePrefixes)) {
    // Real uploads. Most of what a prefix sweep returns is artwork, splashes
    // and other non-icon files, so the ` Icon.png` filter does the real work.
    const uploads = await sweep(host, 'allimages', { aiprefix: `${prefix} `, ailimit: 500 });

    // File redirects. `allimages` lists uploads only, so the punctuated
    // in-game spellings (`Ninja Record: Sound Hunt`) — which exist on the wiki
    // as redirects to a colon-less upload — are invisible to it.
    const redirects = await sweep(host, 'allpages', {
      apnamespace: 6,
      apfilterredir: 'redirects',
      apprefix: `${prefix} `,
      aplimit: 500,
    });

    const { icons, spellings } = namesFromSweeps(prefix, uploads, redirects);
    for (const name of [...icons, ...spellings]) names.add(name);

    console.log(
      `  ${kind}: ${icons.length} icons + ${spellings.length} redirect spellings ` +
        `(${uploads.length} uploads, ${redirects.length} redirects scanned under "${prefix} ")`,
    );
  }

  return names;
}

function report(plan: WritePlan): void {
  console.log(`  miss list (committed, not returned by this sweep): ${plan.removed.join(', ') || 'none'}`);
  if (plan.added.length) console.log(`  + ${plan.added.join('\n  + ')}`);
  if (plan.removed.length) console.log(`  - ${plan.removed.join('\n  - ')}`);
}

async function main(): Promise<void> {
  const force = process.argv.includes('--force');

  for (const game of GAME_KEYS) {
    if (!PORTRAIT_CONFIGS[game]) {
      console.log(`${game}: no portrait config — skipped`);
      continue;
    }

    console.log(`${game}: sweeping ${GAME_CONFIGS[game].host}`);
    const fresh = await sweepGame(game);
    const committed = await readCommitted(game);
    const plan = planWrite(committed, fresh, force);
    console.log(`  ${fresh.size} names (+${plan.added.length}, -${plan.removed.length})`);
    report(plan);

    if (plan.refused) {
      console.error(
        `${game}: refusing to write — ${plan.removed.length} name(s) would be dropped. ` +
          `Read the list above; re-run with \`--force\` to accept it.`,
      );
      process.exitCode = 1;
      continue;
    }

    if (!plan.write) {
      console.log(`${game}: unchanged`);
      continue;
    }

    const path = fileURLToPath(manifestUrl(game));
    writeFileSync(path, renderManifest(game, [...fresh]), 'utf8');
    console.log(`${game}: wrote ${path}`);
  }
}

// Importable for tests; only sweeps the wikis when run as a script.
if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  main().catch((e) => {
    console.error(e);
    process.exitCode = 1;
  });
}
